language: ruby

services:
  - mysql

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --full-index

env:
  - "RAILS_ENV=test"

before_script:
  - cp .travis.database.yml config/database.yml
  - RAILS_ENV=test rake db:create db:migrate

script:
  - bundle exec rspec
