# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f12fc7cde6c5dea6a44a30887c0b67ef7b1d70f3df06fe9ab3808ba906e1d1b388102b3aed8b6213a1f3466da8037d73fa7e86b60017d38d8bc8d56fcfb7d91
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>

test:
  secret_key_base: 1e9a4460e5121e7c6678922dba59bdf5929c79ad877b6759b58b4564703cdaa74835a9081fcffcbad748342395188121f60f508e57badf13bf001539587e2bba
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>